[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -ra --strict-markers
markers =
    e2e: mark test as live end-to-end integration test
filterwarnings =
    ignore::DeprecationWarning
